/**
 * Domain-neutral mock records.
 * Named generically ("items") so this starter kit can become the
 * frontend for finance, grocery, booking, CRM, etc. without a
 * rename. Rename/extend the fields to match your real domain and
 * point services/api.js at a real endpoint later.
 */
export const CATEGORIES = ['All', 'Active', 'Pending', 'Archived', 'Flagged'];

export const MOCK_ITEMS = [
  { id: 'itm_01', title: 'Riverside Studio Renewal', subtitle: 'Contract · Due in 4 days', category: 'Pending', amount: 1240.0, status: 'pending', updatedAt: '2026-09-14T09:12:00Z', icon: 'file-signature' },
  { id: 'itm_02', title: 'Northgate Supply Run', subtitle: 'Order #48213', category: 'Active', amount: 312.5, status: 'active', updatedAt: '2026-09-15T14:02:00Z', icon: 'truck-fast' },
  { id: 'itm_03', title: 'Q3 Client Retainer', subtitle: 'Invoice sent', category: 'Active', amount: 4800.0, status: 'active', updatedAt: '2026-09-13T11:45:00Z', icon: 'file-invoice-dollar' },
  { id: 'itm_04', title: 'Warehouse Utility Audit', subtitle: 'Flagged for review', category: 'Flagged', amount: 96.2, status: 'flagged', updatedAt: '2026-09-10T08:30:00Z', icon: 'triangle-exclamation' },
  { id: 'itm_05', title: 'Downtown Loft Booking', subtitle: 'Sept 22 – Sept 26', category: 'Active', amount: 890.0, status: 'active', updatedAt: '2026-09-12T19:20:00Z', icon: 'bed' },
  { id: 'itm_06', title: 'Legacy Vendor Contract', subtitle: 'Closed out', category: 'Archived', amount: 2100.0, status: 'archived', updatedAt: '2026-08-30T10:00:00Z', icon: 'box-archive' },
  { id: 'itm_07', title: 'Team Onboarding Kit', subtitle: 'Shipped to 3 recipients', category: 'Active', amount: 145.75, status: 'active', updatedAt: '2026-09-15T07:55:00Z', icon: 'boxes-stacked' },
  { id: 'itm_08', title: 'Annual Compliance Review', subtitle: 'Awaiting signature', category: 'Pending', amount: 0, status: 'pending', updatedAt: '2026-09-11T16:10:00Z', icon: 'clipboard-check' },
  { id: 'itm_09', title: 'Household Utilities — Sept', subtitle: 'Auto-pay scheduled', category: 'Active', amount: 214.9, status: 'active', updatedAt: '2026-09-09T06:40:00Z', icon: 'bolt' },
  { id: 'itm_10', title: 'Duplicate Charge Dispute', subtitle: 'Flagged by system', category: 'Flagged', amount: 58.0, status: 'flagged', updatedAt: '2026-09-08T13:15:00Z', icon: 'circle-exclamation' },
];

export function detailFor(item) {
  return {
    ...item,
    reference: `REF-${item.id.toUpperCase()}`,
    timeline: [
      { label: 'Created', date: '2026-09-01', done: true },
      { label: 'Reviewed', date: '2026-09-06', done: true },
      { label: item.status === 'archived' ? 'Closed' : 'Current stage', date: '2026-09-12', done: item.status !== 'pending' },
      { label: 'Finalized', date: '—', done: item.status === 'archived' },
    ],
    notes:
      'This record was generated by the mock data service. Replace services/api.js with real endpoint calls and this detail view updates automatically — no screen changes required.',
  };
}
